export const actionTypes = {
  GET_WEATHER_REPORT_STARTED: "GET_WEATHER_REPORT_STARTED",
  GET_WEATHER_REPORT_SUCCESS: "GET_WEATHER_REPORT_SUCCESS",
  GET_WEATHER_REPORT_FAILURE: "GET_WEATHER_REPORT_FAILURE"

};
